In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [8]:
df = pd.read_csv("./magellan-vector/test_s1.csv")

In [7]:
df

,_id,ltable_id,rtable_id,id_id_exm,id_id_anm,id_id_lev_dist,id_id_lev_sim,title_title_jac_qgm_3_qgm_3,title_title_cos_dlm_dc0_dlm_dc0,authors_authors_jac_qgm_3_qgm_3,authors_authors_cos_dlm_dc0_dlm_dc0,authors_authors_mel,authors_authors_lev_dist,authors_authors_lev_sim,year_year_exm,year_year_anm,year_year_lev_dist,year_year_lev_sim,label
0,0,1496,1225,0.0,0.818850,3.0,0.250000,0.346154,0.530330,0.189007,0.288202,0.616088,45.570435,0.269902,0.270736,0.998779,1.771518,0.704747,0
1,1,574,749,0.0,0.766355,2.0,0.333333,0.256410,0.377964,0.189007,0.288202,0.616088,45.570435,0.269902,0.270736,0.998779,1.771518,0.704747,0
2,2,561,1957,0.0,0.286663,4.0,0.000000,0.193939,0.314270,0.189007,0.288202,0.616088,45.570435,0.269902,1.000000,1.000000,0.000000,1.000000,0
3,3,1799,1307,0.0,0.726515,3.0,0.250000,0.195266,0.158114,0.189007,0.288202,0.616088,45.570435,0.269902,0.270736,0.998779,1.771518,0.704747,0
4,4,1116,1205,0.0,0.926141,3.0,0.250000,0.151020,0.134840,0.189007,0.288202,0.616088,45.570435,0.269902,0.270736,0.998779,1.771518,0.704747,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2468,2468,2202,1324,0.0,0.601272,4.0,0.000000,0.410072,0.529813,0.189007,0.288202,0.616088,45.570435,0.269902,1.000000,1.000000,0.000000,1.000000,1
2469,2469,94,2277,0.0,0.041282,4.0,0.000000,0.177305,0.226134,0.189007,0.288202,0.616088,45.570435,0.269902,0.270736,0.998779,1.771518,0.704747,0
2470,2470,5,1921,0.0,0.002603,4.0,0.000000,0.238095,0.412021,0.189007,0.288202,0.616088,45.570435,0.269902,0.000000,0.998999,1.000000,0.833333,0
2471,2471,2451,539,0.0,0.219910,4.0,0.000000,0.421053,0.483494,0.189007,0.288202,0.616088,45.570435,0.269902,1.000000,1.000000,0.000000,1.000000,1
2472,2472,1577,518,0.0,0.328472,3.0,0.250000,0.216216,0.301511,0.189007,0.288202,0.616088,45.570435,0.269902,0.000000,0.998002,4.000000,0.333333,0

In [10]:
df = pd.read_csv("./processed_vectors_structured/data_1_test.csv")

In [11]:
df

,Unnamed: 0,true___str___affine___ltable_id___rtable_id,true___str___lev_dist___ltable_id___rtable_id,true___str___lev_sim___ltable_id___rtable_id,true___str___jaro___ltable_id___rtable_id,true___str___jaro_winker___ltable_id___rtable_id,true___str___needleman_wunsch___ltable_id___rtable_id,true___str___smith_waterman___ltable_id___rtable_id,true___str___exact_match___ltable_id___rtable_id,true___str___monge_elkan___ltable_id___rtable_id,...,true___arr___overlap_coeff___space___ltable_price___rtable_price,true___arr___jaccard___3gram___ltable_price___rtable_price,true___arr___jaccard___space___ltable_price___rtable_price,true___arr___dice___3gram___ltable_price___rtable_price,true___arr___dice___space___ltable_price___rtable_price,true___arr___cosine___3gram___ltable_price___rtable_price,true___arr___cosine___space___ltable_price___rtable_price,true___num___abs_norm___ltable_price___rtable_price,true___num___rel_diff___ltable_price___rtable_price,label
0,0,0.0,3,0.00,0.000000,0.000000,0.0,1.0,0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.005882,1.976611,0
1,1,0.0,3,0.00,0.000000,0.000000,0.0,0.0,0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.240363,1.224863,0
2,2,-1.0,4,0.00,0.000000,0.000000,-1.0,0.0,0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.830518,0.185174,0
3,3,0.0,3,0.25,0.527778,0.527778,0.0,1.0,0,0.527778,...,0.0,0.076923,0.0,0.142857,0.0,0.142857,0.0,0.698566,0.354927,0
4,4,1.0,3,0.25,0.666667,0.666667,1.0,1.0,0,0.666667,...,0.0,0.400000,0.0,0.571429,0.0,0.571429,0.0,0.332220,1.002506,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2288,2288,-1.0,4,0.00,0.000000,0.000000,-1.0,0.0,0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,2.000000,0
2289,2289,0.0,3,0.25,0.527778,0.527778,0.0,1.0,0,0.527778,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.027010,1.894801,0
2290,2290,0.0,3,0.00,0.000000,0.000000,0.0,0.0,0,0.000000,...,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.688168,0.369432,0
2291,2291,0.0,4,0.00,0.000000,0.000000,0.0,1.0,0,0.000000,...,0.0,0.500000,0.0,0.666667,0.0,0.668153,0.0,0.444414,0.769290,0
2292,2292,0.0,3,0.25,0.527778,0.527778,0.0,1.0,0,0.527778,...,0.0,0.066667,0.0,0.125000,0.0,0.125000,0.0,0.685784,0.372784,0